// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MySolarCellsSQLite.Sqlite;

#nullable disable

namespace MySolarCellsSQLite.Migrations
{
    [DbContext(typeof(MscDbContext))]
    [Migration("20240324141535_Refactoring")]
    partial class Refactoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("MySolarCellsSQLite.Sqlite.Models.Energy", b =>
                {
                    b.Property<int>("EnergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BatteryCharge")
                        .HasColumnType("REAL");

                    b.Property<bool>("BatterySynced")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BatteryUsed")
                        .HasColumnType("REAL");

                    b.Property<double>("BatteryUsedProfit")
                        .HasColumnType("REAL");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("ElectricitySupplierProductionSold")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElectricitySupplierPurchased")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InverterTypProductionOwnUse")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PriceLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("ProductionOwnUse")
                        .HasColumnType("REAL");

                    b.Property<double>("ProductionOwnUseProfit")
                        .HasColumnType("REAL");

                    b.Property<bool>("ProductionOwnUseSynced")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ProductionSold")
                        .HasColumnType("REAL");

                    b.Property<double>("ProductionSoldProfit")
                        .HasColumnType("REAL");

                    b.Property<bool>("ProductionSoldSynced")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Purchased")
                        .HasColumnType("REAL");

                    b.Property<double>("PurchasedCost")
                        .HasColumnType("REAL");

                    b.Property<bool>("PurchasedSynced")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("UnitPriceBuy")
                        .HasColumnType("REAL");

                    b.Property<double>("UnitPriceSold")
                        .HasColumnType("REAL");

                    b.Property<double>("UnitPriceVatBuy")
                        .HasColumnType("REAL");

                    b.Property<double>("UnitPriceVatSold")
                        .HasColumnType("REAL");

                    b.HasKey("EnergyId");

                    b.HasIndex("Timestamp")
                        .IsUnique();

                    b.ToTable("Energy");
                });

            modelBuilder.Entity("MySolarCellsSQLite.Sqlite.Models.EnergyCalculationParameter", b =>
                {
                    b.Property<int>("EnergyCalculationParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("EnergyTax")
                        .HasColumnType("REAL");

                    b.Property<double>("FixedPriceKwh")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ProdCompensationElectricityLowLoad")
                        .HasColumnType("REAL");

                    b.Property<double>("TaxReduction")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalInstallKwhPanels")
                        .HasColumnType("REAL");

                    b.Property<double>("TransferFee")
                        .HasColumnType("REAL");

                    b.Property<bool>("UseSpotPrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("EnergyCalculationParameterId");

                    b.HasIndex("FromDate")
                        .IsUnique();

                    b.ToTable("EnergyCalculationParameter");
                });

            modelBuilder.Entity("MySolarCellsSQLite.Sqlite.Models.Home", b =>
                {
                    b.Property<int>("HomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ElectricitySupplier")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ImportOnlySpotPrice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubSystemEntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("HomeId");

                    b.ToTable("Home");
                });

            modelBuilder.Entity("MySolarCellsSQLite.Sqlite.Models.Inverter", b =>
                {
                    b.Property<int>("InverterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiUrl")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InverterTyp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubSystemEntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("InverterId");

                    b.ToTable("Inverter");
                });

            modelBuilder.Entity("MySolarCellsSQLite.Sqlite.Models.InvestmentAndLoan", b =>
                {
                    b.Property<int>("InvestmentAndLoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Investment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Loan")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvestmentAndLoanId");

                    b.HasIndex("FromDate")
                        .IsUnique();

                    b.ToTable("InvestmentAndLon");
                });

            modelBuilder.Entity("MySolarCellsSQLite.Sqlite.Models.InvestmentAndLoanInterest", b =>
                {
                    b.Property<int>("InvestmentAndLoanInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amortization")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("Interest")
                        .HasColumnType("REAL");

                    b.Property<int>("InvestmentAndLoanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvestmentAndLoanInterestId");

                    b.HasIndex("InvestmentAndLoanId");

                    b.HasIndex("FromDate", "InvestmentAndLoanId")
                        .IsUnique();

                    b.ToTable("InvestmentAndLonInterest");
                });

            modelBuilder.Entity("MySolarCellsSQLite.Sqlite.Models.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogDetails")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("LogTyp")
                        .HasColumnType("INTEGER");

                    b.HasKey("LogId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("MySolarCellsSQLite.Sqlite.Models.PowerTariffParameters", b =>
                {
                    b.Property<int>("PowerTariffParametersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountOfPeaksToUse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayTimeEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayTimeStart")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodMonthEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodMonthStart")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PricePerKwh")
                        .HasColumnType("REAL");

                    b.Property<bool>("UsePeaksFromSameDay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Weekday")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Weekend")
                        .HasColumnType("INTEGER");

                    b.HasKey("PowerTariffParametersId");

                    b.ToTable("PowerTariffParameters");
                });

            modelBuilder.Entity("MySolarCellsSQLite.Sqlite.Models.Preferences", b =>
                {
                    b.Property<int>("PreferencesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateValue")
                        .HasColumnType("TEXT");

                    b.Property<double>("DoubleValue")
                        .HasColumnType("REAL");

                    b.Property<int>("IntValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StringValue")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PreferencesId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("MySolarCellsSQLite.Sqlite.Models.SavingEstimateParameters", b =>
                {
                    b.Property<int>("SavingEstimateParametersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PanelDegradationPerYear")
                        .HasColumnType("REAL");

                    b.Property<double>("RealDevelopmentElectricityPrice")
                        .HasColumnType("REAL");

                    b.HasKey("SavingEstimateParametersId");

                    b.ToTable("SavingEstimateParameters");
                });

            modelBuilder.Entity("MySolarCellsSQLite.Sqlite.Models.InvestmentAndLoanInterest", b =>
                {
                    b.HasOne("MySolarCellsSQLite.Sqlite.Models.InvestmentAndLoan", null)
                        .WithMany("Interest")
                        .HasForeignKey("InvestmentAndLoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MySolarCellsSQLite.Sqlite.Models.InvestmentAndLoan", b =>
                {
                    b.Navigation("Interest");
                });
#pragma warning restore 612, 618
        }
    }
}
