//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySolarCells.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySolarCells.Resources.Translations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Token.
        /// </summary>
        public static string Access_Token {
            get {
                return ResourceManager.GetString("Access_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add battery.
        /// </summary>
        public static string Add_Battery {
            get {
                return ResourceManager.GetString("Add_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amortization.
        /// </summary>
        public static string Amortization {
            get {
                return ResourceManager.GetString("Amortization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api key.
        /// </summary>
        public static string Api_Key {
            get {
                return ResourceManager.GetString("Api_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api url.
        /// </summary>
        public static string Api_Url {
            get {
                return ResourceManager.GetString("Api_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application version.
        /// </summary>
        public static string Application_Version {
            get {
                return ResourceManager.GetString("Application_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average battery used saved/Kwh.
        /// </summary>
        public static string Average_Battery_Used_Saved_Per_Kwh {
            get {
                return ResourceManager.GetString("Average_Battery_Used_Saved_Per_Kwh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average production own use saved/Kwh.
        /// </summary>
        public static string Average_Production_Own_Use_Saved_Per_Kwh {
            get {
                return ResourceManager.GetString("Average_Production_Own_Use_Saved_Per_Kwh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average production sold profit/kWh.
        /// </summary>
        public static string Average_Production_Sold_Profit_Per_Kwh {
            get {
                return ResourceManager.GetString("Average_Production_Sold_Profit_Per_Kwh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average purchased cost/kWh.
        /// </summary>
        public static string Average_Purchased_Cost_Per_Kwh {
            get {
                return ResourceManager.GetString("Average_Purchased_Cost_Per_Kwh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance (production minus consumption).
        /// </summary>
        public static string Balance_Production_Minus_Consumption {
            get {
                return ResourceManager.GetString("Balance_Production_Minus_Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        public static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery charge.
        /// </summary>
        public static string Battery_Charge {
            get {
                return ResourceManager.GetString("Battery_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery SEK.
        /// </summary>
        public static string Battery_Currency {
            get {
                return ResourceManager.GetString("Battery_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery energy tax.
        /// </summary>
        public static string Battery_Energy_Tax {
            get {
                return ResourceManager.GetString("Battery_Energy_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery kWh.
        /// </summary>
        public static string Battery_Kwh {
            get {
                return ResourceManager.GetString("Battery_Kwh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery transfer fee.
        /// </summary>
        public static string Battery_Transfer_Fee {
            get {
                return ResourceManager.GetString("Battery_Transfer_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery used.
        /// </summary>
        public static string Battery_used {
            get {
                return ResourceManager.GetString("Battery_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy (transfer fee/tax).
        /// </summary>
        public static string Buy_Transfer_Fee_Tax {
            get {
                return ResourceManager.GetString("Buy_Transfer_Fee_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation factors.
        /// </summary>
        public static string Calculation_Factors {
            get {
                return ResourceManager.GetString("Calculation_Factors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation factors for costs and revenues related to solar cell production..
        /// </summary>
        public static string Calculation_Factors_Intro_Text {
            get {
                return ResourceManager.GetString("Calculation_Factors_Intro_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation parameters.
        /// </summary>
        public static string Calculation_Parameters {
            get {
                return ResourceManager.GetString("Calculation_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation electricity load.
        /// </summary>
        public static string Compensation_Electricity_Load {
            get {
                return ResourceManager.GetString("Compensation_Electricity_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation for production to grid.
        /// </summary>
        public static string Compensation_For_Production_To_Grid {
            get {
                return ResourceManager.GetString("Compensation_For_Production_To_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption.
        /// </summary>
        public static string Consumption {
            get {
                return ResourceManager.GetString("Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costs and revenues.
        /// </summary>
        public static string Costs_And_Rvenues {
            get {
                return ResourceManager.GetString("Costs_And_Rvenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEK.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity supplier.
        /// </summary>
        public static string Electricity_Supplier {
            get {
                return ResourceManager.GetString("Electricity_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy tax.
        /// </summary>
        public static string Energy_Tax {
            get {
                return ResourceManager.GetString("Energy_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy tax (comsumption).
        /// </summary>
        public static string Energy_Tax_Comsumption {
            get {
                return ResourceManager.GetString("Energy_Tax_Comsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error import data from inverter.
        /// </summary>
        public static string Error_Import_Data_From_Inverter {
            get {
                return ResourceManager.GetString("Error_Import_Data_From_Inverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string Export_To_Excel {
            get {
                return ResourceManager.GetString("Export_To_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now its time to get all you historic data please don&apos;t turn of the app or switch to other app.
        /// </summary>
        public static string First_Import_Intro_Text {
            get {
                return ResourceManager.GetString("First_Import_Intro_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed price/Kwh.
        /// </summary>
        public static string Fixed_Price_Kwh {
            get {
                return ResourceManager.GetString("Fixed_Price_Kwh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string From_Date {
            get {
                return ResourceManager.GetString("From_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fun facts.
        /// </summary>
        public static string Fun_Facts {
            get {
                return ResourceManager.GetString("Fun_Facts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating report please wait.
        /// </summary>
        public static string Generating_Report_Please_Wait {
            get {
                return ResourceManager.GetString("Generating_Report_Please_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto Tibber Api site.
        /// </summary>
        public static string Goto_Tibber_Api_Site {
            get {
                return ResourceManager.GetString("Goto_Tibber_Api_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If battery is not used.
        /// </summary>
        public static string If_Battery_Is_Not_Used {
            get {
                return ResourceManager.GetString("If_Battery_Is_Not_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data.
        /// </summary>
        public static string Import_Data {
            get {
                return ResourceManager.GetString("Import_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data from electricity supplier..
        /// </summary>
        public static string Import_Data_From_Electricity_Supplier {
            get {
                return ResourceManager.GetString("Import_Data_From_Electricity_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data from electricity supplier Done.
        /// </summary>
        public static string Import_Data_From_Electricity_Supplier_Done {
            get {
                return ResourceManager.GetString("Import_Data_From_Electricity_Supplier_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import data from inverter.
        /// </summary>
        public static string Import_Data_From_Inverter {
            get {
                return ResourceManager.GetString("Import_Data_From_Inverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import of production done.
        /// </summary>
        public static string Import_Of_Production_Done {
            get {
                return ResourceManager.GetString("Import_Of_Production_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import only spot prices.
        /// </summary>
        public static string Import_Only_Spot_Prices {
            get {
                return ResourceManager.GetString("Import_Only_Spot_Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this if you get consumption and production from Inverter and only need Tibber for the Spot price per hour..
        /// </summary>
        public static string Import_Only_Spot_Prices_Desc {
            get {
                return ResourceManager.GetString("Import_Only_Spot_Prices_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing data from your inverter ended as it only allows {0} days of sync per day. You impored {1} days, now have data up to {2}.
        /// </summary>
        public static string Importing_Data_From_Your_Inverter_Ended_As_It_Only_Allows_And_More {
            get {
                return ResourceManager.GetString("Importing_Data_From_Your_Inverter_Ended_As_It_Only_Allows_And_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to retrieve information from Tibber, we need an Access Token. You can get it by click on &apos;Goto Tibber Api site&apos; below. Copy/paste the api key in to the field below..
        /// </summary>
        public static string In_Order_To_Retrieve_Information_From_Tibber_And_More {
            get {
                return ResourceManager.GetString("In_Order_To_Retrieve_Information_From_Tibber_And_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install date.
        /// </summary>
        public static string Install_Date {
            get {
                return ResourceManager.GetString("Install_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install year.
        /// </summary>
        public static string Install_Year {
            get {
                return ResourceManager.GetString("Install_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest.
        /// </summary>
        public static string Interest {
            get {
                return ResourceManager.GetString("Interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest saved.
        /// </summary>
        public static string Interest_Saved {
            get {
                return ResourceManager.GetString("Interest_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverter.
        /// </summary>
        public static string Inverter {
            get {
                return ResourceManager.GetString("Inverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment.
        /// </summary>
        public static string Investment {
            get {
                return ResourceManager.GetString("Investment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment and loan.
        /// </summary>
        public static string Investment_And_Loan {
            get {
                return ResourceManager.GetString("Investment_And_Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can enter the investment and any loans taken out for your installation.
        /// </summary>
        public static string Investment_Loan_Intro_Text {
            get {
                return ResourceManager.GetString("Investment_Loan_Intro_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment and loan.
        /// </summary>
        public static string Investment_slash_Loan {
            get {
                return ResourceManager.GetString("Investment_slash_Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the same login as in the kostal app/Kostal web portal login.
        /// </summary>
        public static string Kostal_Intro_Guide_Text {
            get {
                return ResourceManager.GetString("Kostal_Intro_Guide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kWh.
        /// </summary>
        public static string kWh {
            get {
                return ResourceManager.GetString("kWh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KWh from battery.
        /// </summary>
        public static string KWh_From_Battery {
            get {
                return ResourceManager.GetString("KWh_From_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left of investment cost.
        /// </summary>
        public static string Left_Of_Investment_Cost {
            get {
                return ResourceManager.GetString("Left_Of_Investment_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan (press &apos;Add&apos; for adding interest information).
        /// </summary>
        public static string Loan_Press_Add_For_Adding_Interest_Information {
            get {
                return ResourceManager.GetString("Loan_Press_Add_For_Adding_Interest_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed {0} sec tax reduction, production higher than consumption..
        /// </summary>
        public static string Missed_Value_Tax_Reduction_Production_Higher_Than_Consumption {
            get {
                return ResourceManager.GetString("Missed_Value_Tax_Reduction_Production_Higher_Than_Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move on.
        /// </summary>
        public static string Move_On {
            get {
                return ResourceManager.GetString("Move_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My description.
        /// </summary>
        public static string My_Description {
            get {
                return ResourceManager.GetString("My_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My solar cells.
        /// </summary>
        public static string My_Solar_Cells {
            get {
                return ResourceManager.GetString("My_Solar_Cells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own use.
        /// </summary>
        public static string Own_Use {
            get {
                return ResourceManager.GetString("Own_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own use saved cost.
        /// </summary>
        public static string Own_Use_Saved_Cost {
            get {
                return ResourceManager.GetString("Own_Use_Saved_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own use saved energy tax.
        /// </summary>
        public static string Own_Use_Saved_Energy_Tax {
            get {
                return ResourceManager.GetString("Own_Use_Saved_Energy_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own Use Saved Transfer Fee.
        /// </summary>
        public static string Own_Use_Saved_Transfer_Fee {
            get {
                return ResourceManager.GetString("Own_Use_Saved_Transfer_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak use production own use Kwh/Hour.
        /// </summary>
        public static string Peak_Use_Production_And_Own_Use_Kwh_Hour {
            get {
                return ResourceManager.GetString("Peak_Use_Production_And_Own_Use_Kwh_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak use production kwh/hour.
        /// </summary>
        public static string Peak_Use_Production_Kwh_Hour {
            get {
                return ResourceManager.GetString("Peak_Use_Production_Kwh_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the brand of your electricity supplier.
        /// </summary>
        public static string Pick_The_Brand_Of_Your_Electricity_Supplier {
            get {
                return ResourceManager.GetString("Pick_The_Brand_Of_Your_Electricity_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the brand of your electricity supplier.
        /// </summary>
        public static string Pick_The_Electricity_Supplier_Intro_Text {
            get {
                return ResourceManager.GetString("Pick_The_Electricity_Supplier_Intro_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick the invert from the list below that represent you installation.
        /// </summary>
        public static string Pick_The_Invert_Desc {
            get {
                return ResourceManager.GetString("Pick_The_Invert_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick your site.
        /// </summary>
        public static string Pick_Your_Site {
            get {
                return ResourceManager.GetString("Pick_Your_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices.
        /// </summary>
        public static string Prices {
            get {
                return ResourceManager.GetString("Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production And consumption.
        /// </summary>
        public static string Production_And_Consumption {
            get {
                return ResourceManager.GetString("Production_And_Consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production grid compensation.
        /// </summary>
        public static string Production_Grid_Compensation {
            get {
                return ResourceManager.GetString("Production_Grid_Compensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production index (prod/day).
        /// </summary>
        public static string Production_Index_Desc_Prod_Per_Day_KWh {
            get {
                return ResourceManager.GetString("Production_Index_Desc_Prod_Per_Day_KWh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production own use.
        /// </summary>
        public static string Production_Own_Use {
            get {
                return ResourceManager.GetString("Production_Own_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production profit sold.
        /// </summary>
        public static string Production_Profit_Sold {
            get {
                return ResourceManager.GetString("Production_Profit_Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production saved energy tax.
        /// </summary>
        public static string Production_Saved_Energy_Tax {
            get {
                return ResourceManager.GetString("Production_Saved_Energy_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production sold.
        /// </summary>
        public static string Production_Sold {
            get {
                return ResourceManager.GetString("Production_Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production to grid.
        /// </summary>
        public static string Production_To_Grid {
            get {
                return ResourceManager.GetString("Production_To_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        public static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase cost.
        /// </summary>
        public static string Purchase_Cost {
            get {
                return ResourceManager.GetString("Purchase_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase energy tax.
        /// </summary>
        public static string Purchase_Energy_Tax {
            get {
                return ResourceManager.GetString("Purchase_Energy_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase transfer fee.
        /// </summary>
        public static string Purchase_Transfer_Fee {
            get {
                return ResourceManager.GetString("Purchase_Transfer_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchased.
        /// </summary>
        public static string Purchased {
            get {
                return ResourceManager.GetString("Purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove battery.
        /// </summary>
        public static string Remove_Battery {
            get {
                return ResourceManager.GetString("Remove_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROI.
        /// </summary>
        public static string ROI {
            get {
                return ResourceManager.GetString("ROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved cost.
        /// </summary>
        public static string Saved_Cost {
            get {
                return ResourceManager.GetString("Saved_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved cost battery.
        /// </summary>
        public static string Saved_Cost_Battery {
            get {
                return ResourceManager.GetString("Saved_Cost_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved energy tax.
        /// </summary>
        public static string Saved_Energy_Tax {
            get {
                return ResourceManager.GetString("Saved_Energy_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved energy tax battery.
        /// </summary>
        public static string Saved_Energy_Tax_Battery {
            get {
                return ResourceManager.GetString("Saved_Energy_Tax_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved rows {0}.
        /// </summary>
        public static string Saved_Rows_Amount {
            get {
                return ResourceManager.GetString("Saved_Rows_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved transfer fee.
        /// </summary>
        public static string Saved_Transfer_Fee {
            get {
                return ResourceManager.GetString("Saved_Transfer_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved transfer fee battery.
        /// </summary>
        public static string Saved_Transfer_Fee_Battery {
            get {
                return ResourceManager.GetString("Saved_Transfer_Fee_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the home you want to analyze.
        /// </summary>
        public static string Select_The_Home_You_Want_To_Analyze {
            get {
                return ResourceManager.GetString("Select_The_Home_You_Want_To_Analyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell (tax red../net ben..).
        /// </summary>
        public static string Sell_Tax_Red_Net_Ben {
            get {
                return ResourceManager.GetString("Sell_Tax_Red_Net_Ben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate.
        /// </summary>
        public static string Simulate {
            get {
                return ResourceManager.GetString("Simulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate battery.
        /// </summary>
        public static string Simulate_Battery {
            get {
                return ResourceManager.GetString("Simulate_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account users should generate an Account Level API Key from https://monitoring.solaredge.com.
        /// </summary>
        public static string SolarEdge_Intro_Guide_Text {
            get {
                return ResourceManager.GetString("SolarEdge_Intro_Guide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold.
        /// </summary>
        public static string Sold {
            get {
                return ResourceManager.GetString("Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start import.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step {0} of {1} {2}.
        /// </summary>
        public static string Step_Nr_of_Nr_InfoText {
            get {
                return ResourceManager.GetString("Step_Nr_of_Nr_InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support and feedback.
        /// </summary>
        public static string Support_And_Feedback {
            get {
                return ResourceManager.GetString("Support_And_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization not started as we have all data up to the previous full hour..
        /// </summary>
        public static string Synchronization_Not_Started_As_We_Have_All_Data_And_More {
            get {
                return ResourceManager.GetString("Synchronization_Not_Started_As_We_Have_All_Data_And_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax reduction.
        /// </summary>
        public static string Tax_Reduction {
            get {
                return ResourceManager.GetString("Tax_Reduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax reduction (produced/kWh to grid).
        /// </summary>
        public static string Tax_Reduction_Discription {
            get {
                return ResourceManager.GetString("Tax_Reduction_Discription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login failed, check that you entered the correct information.
        /// </summary>
        public static string The_Login_Failed_Check_That_You_Entered_The_Correct_Information {
            get {
                return ResourceManager.GetString("The_Login_Failed_Check_That_You_Entered_The_Correct_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data to show on this date.
        /// </summary>
        public static string There_Is_No_Data_To_Show_On_This_Date {
            get {
                return ResourceManager.GetString("There_Is_No_Data_To_Show_On_This_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tibber.
        /// </summary>
        public static string Tibber {
            get {
                return ResourceManager.GetString("Tibber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use Tibber you ned your private API key. You can get that by click on the button below and login..
        /// </summary>
        public static string Tibber_Guide_Text {
            get {
                return ResourceManager.GetString("Tibber_Guide_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools and features.
        /// </summary>
        public static string Tools_And_Features {
            get {
                return ResourceManager.GetString("Tools_And_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total installed Kwh.
        /// </summary>
        public static string Total_Installed_Kwh {
            get {
                return ResourceManager.GetString("Total_Installed_Kwh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total installed panels (kWh).
        /// </summary>
        public static string Total_Installed_Panels_Kwh {
            get {
                return ResourceManager.GetString("Total_Installed_Panels_Kwh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total interest.
        /// </summary>
        public static string Total_Interest {
            get {
                return ResourceManager.GetString("Total_Interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total investment and loan.
        /// </summary>
        public static string Total_Investment_And_Loan {
            get {
                return ResourceManager.GetString("Total_Investment_And_Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total produced and saved.
        /// </summary>
        public static string Total_Produced_And_Saved {
            get {
                return ResourceManager.GetString("Total_Produced_And_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total production.
        /// </summary>
        public static string Total_Production {
            get {
                return ResourceManager.GetString("Total_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total production (sold/own use).
        /// </summary>
        public static string Total_Production_Sold_Own_Use {
            get {
                return ResourceManager.GetString("Total_Production_Sold_Own_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total purchased.
        /// </summary>
        public static string Total_Purchased {
            get {
                return ResourceManager.GetString("Total_Purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer fee.
        /// </summary>
        public static string Transfer_Fee {
            get {
                return ResourceManager.GetString("Transfer_Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Spot prices.
        /// </summary>
        public static string Use_Spot_Prices {
            get {
                return ResourceManager.GetString("Use_Spot_Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years left until ROI.
        /// </summary>
        public static string Years_Left_Until_ROI {
            get {
                return ResourceManager.GetString("Years_Left_Until_ROI", resourceCulture);
            }
        }
    }
}
